version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build:
       context: .
       dockerfile: Dockerfile
       args:
        - PASSWORD_ENV_SEEDED=password

    image: taxmanager
    container_name: taxmanager_application
    ports:
      - "5000:80"
      - "5005:443"
    environment:
      - PASSWORD_ENV_SEEDED=password
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password